public enum TipoToken {

    PROGRAM, PROCEDURE, FUNCTION, IDENTIFICADOR, PUNTO_Y_COMA,

    VAR, COMA, DOS_PUNTOS, INTEGER, BOOLEAN,

    BEGIN, END, PUNTO,

    ASIGNACION,

    NUMERO,

    MAS, MENOS, MULTIPLICACION,

    DIV, AND, OR, NOT,

    IF, THEN, ELSE,

    WHILE, DO,

    WRITE, READ,

    PARENTESIS_ABRE, PARENTESIS_CIERRA,

    IGUAL, DISTINTO, MENOR, MENOR_IGUAL,

    MAYOR, MAYOR_IGUAL,

    FIN_ARCHIVO
}